FROM ubuntu:16.04

## Container's mount point for the host's input/output folder
VOLUME "/host"

RUN apt-get update &&                          \
    apt-get install -y --no-install-recommends \
        vim

